services:
  - type: web
    name: crm-eclat-net
    env: node
    plan: free
    region: oregon
    buildCommand: |
      echo "Installing frontend dependencies..."
      cd frontend
      npm install
      echo "Building frontend..."
      npm run build
      echo "Installing backend dependencies..."
      cd ../backend
      npm install
      echo "Building backend..."
      npm run build
      echo "Build completed successfully!"
    startCommand: |
      cd backend
      node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: crm-database
          property: connectionString

databases:
  - name: crm-database
    plan: free
    region: oregon